apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-teajdbc
  namespace: ace
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: webapp/tea

  # dest k8s secret
  destination:
    name: vault-teajdbc
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth