apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea-hashicorp-vault
  labels:
    app: tea-hashicorp-vault
spec:
  selector:
    matchLabels:
      app: tea-hashicorp-vault
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-tea: "secret/tea"
        vault.hashicorp.com/agent-inject-template-tea: |
          {{- with secret "secret/tea" -}}
          type={{ .Data.data.type }}
          username={{ .Data.data.username }}
          password={{ .Data.data.password }}
          {{- end }}
        vault.hashicorp.com/role: "teaapp"
      labels:
        app: tea-hashicorp-vault
    spec:
      serviceAccountName: app
      containers:
      - name: tea-hashicorp-vault
        image: image-registry.openshift-image-registry.svc:5000/default/tea-tekton:latest
        env:
        - name: TEA_DATABASE_NAME
          value: 'BLUDB'
        - name: TEA_SERVER_NAME
          value: '9938aec0-8105-433e-8bf9-0fbb7e483086.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud'
        - name: TEA_PORT_NUMBER
          value: '32459'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  labels:
    app: tea-hashicorp-vault
