apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  annotations:
    appconnect.ibm.com/hibernate: 'false'
  name: APP_NAME
  namespace: APP_NAMESPACE
spec:
  flowType:
    toolkitFlow: true
  license:
    accept: true
    license: L-KPRV-AUG9NC
    use: AppConnectEnterpriseNonProductionFREE
  template:
    spec:
      containers:
        - image: >-
            IR_IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          name: runtime
          resources:
            requests:
              cpu: 300m
              memory: 368Mi
      # This is now handled via the "default" service account
      # kubectl patch serviceaccount default --type=json -p='[{"op": "add", "path": "/imagePullSecrets/-", "value": {"name": "regcred"}}]'
      #imagePullSecrets:
      #- name: regcred
  configurations:
    - teajdbc-policy
    - default-policy
    - teajdbc
    # For callable flows; name should match a valid private network connection configuration
    # that connects to the IWHI switch server (not the a local CP4i switch server).
    # - iwhi-private-network-connection
  version: 13.0.4.0-r1
